version: '1.3.{build}'
branches:
  only:
  - master
clone_depth: 10
build:
  verbosity: minimal
os: Windows Server 2012
install:
  - ps: ".\script\appveyor-install-jce.ps1"
  - cinst: maven
  - cmd: refreshenv
environment:
  MAVEN_OPTS: '-Xmx256m'
build_script:
  - mvn clean install -DskipTests
test_script:
  - mvn clean install -Pcodecov 2>&1
